Repository Global-Conflicts-ArmA/Olsen-Framework-Arma-3, pull requests merged in 2022-01, with the labels that each got.

#129 Enhancements to try to ensure players can't move when spectating
  core/CfgFunctions.hpp
  core/functions/spectator/fn_EGSpectator.sqf
  core/functions/spectator/fn_freezeUnit.sqf
  core/functions/spectator/fn_initSpectateScreen.sqf
  core/functions/spectator/fn_startSpectator.sqf
  core/functions/spectator/fn_thawUnit.sqf
Labels: enhancement

#132 Fix: Babel languages in spectator
  modules/acre_setup/functions/ACRESetup/fn_ACRES_ClientInit.sqf
  modules/acre_setup/postInitClient.sqf
  modules/acre_setup/preInitClient.sqf
  modules/acre_setup/root.sqf
Labels: bug

#135 Firemission hc compatibility
  modules/firemission/functions/FIREMIS/fn_FIREMIS_PointFiremission.sqf
  modules/firemission/functions/FIREMIS/fn_FIREMIS_RegisterForwardObserver.sqf
  modules/firemission/preInitClient.sqf
Labels: enhancement

#134 Update: Draw an icon where the player died, for the killcam.
  core/functions/spectator/fn_startSpectator.sqf
Labels: enhancement

#133 Update: Display all briefings in spectator briefing screen.
  core/CfgFunctions.hpp
  core/functions/spectator/fn_handleComboBoxChange.sqf
  core/functions/spectator/fn_handleListChange.sqf
  core/functions/spectator/fn_initSpectateScreen.sqf
  core/functions/spectator/fn_spectatorBriefing.sqf
  core/preinitClient.sqf
Labels: enhancement

#137 Fix: FIREMISSION - Allow markers to be targetted
  modules/firemission/functions/FIREMIS/fn_FIREMIS_GetPointFiremissionText.sqf
  modules/firemission/functions/FIREMIS/fn_FIREMIS_InternalSpottingFiremission.sqf
  modules/firemission/preInitClient.sqf
Labels: bug

#138 Anti nd team settings
  modules/anti_nd/functions/anti_nd/fn_Init.sqf
  modules/anti_nd/preinitClient.sqf
  modules/anti_nd/settings.sqf
Labels: enhancement

#140 change marker check to lazy
  modules/firemission/functions/FIREMIS/fn_FIREMIS_InternalSpottingFiremission.sqf
Labels: bug

#142 Modules.sqf update
  core/script_macros.hpp
  modules/modules.sqf
Labels: enhancement

#141 Firemission - Function to do constant artillery throughout the mission.
  modules/firemission/functions/CfgFunctions.hpp
  modules/firemission/functions/FIREMIS/fn_FIREMIS_DoConstantArtillery.sqf
  modules/firemission/settings.sqf
Labels: enhancement

#144 Currency module
  modules/currency/CfgCurrency.hpp
  modules/currency/functions/CURRENCY/fn_addCurrency.sqf
  modules/currency/functions/CURRENCY/fn_deductCurrency.sqf
  modules/currency/functions/CURRENCY/fn_getCurrency.sqf
  modules/currency/functions/CURRENCY/fn_getCurrencyText.sqf
  modules/currency/functions/CURRENCY/fn_setCurrency.sqf
  modules/currency/functions/CURRENCY/script_component.hpp
  modules/currency/functions/CfgFunctions.hpp
  modules/currency/preInitClient.sqf
  modules/currency/root.sqf
  modules/currency/script_component.hpp
  modules/currency/settings.sqf
  modules/modules.sqf
Labels: enhancement

#146 Paraflare module port
  modules/modules.sqf
  modules/paraflare/ReadMe.md
  modules/paraflare/functions/CfgFunctions.hpp
  modules/paraflare/functions/PARAFL/fn_flareFire.sqf
  modules/paraflare/functions/PARAFL/fn_flareLight.sqf
  modules/paraflare/functions/PARAFL/script_component.hpp
  modules/paraflare/postInitClient.sqf
  modules/paraflare/preInitClient.sqf
  modules/paraflare/root.sqf
  modules/paraflare/script_component.hpp
  modules/paraflare/sounds.hpp
  modules/paraflare/sounds/flareFire.ogg
  modules/paraflare/sounds/flareShell.ogg
Labels: enhancement

#148 Anti ND Vehicle Turret Fix
  modules/anti_nd/functions/anti_nd/fn_Init.sqf
  modules/anti_nd/preinitClient.sqf
Labels: bug

#149 AO Limit Soft - Audible warning setting
  modules/ao_limit_soft/functions/SAOLIM/fn_init.sqf
  modules/ao_limit_soft/preInitClient.sqf
  modules/ao_limit_soft/root.sqf
  modules/ao_limit_soft/settings.sqf
  modules/ao_limit_soft/sounds.hpp
  modules/ao_limit_soft/sounds/alert.ogg
Labels: enhancement

#153 Remove previously renamed modules, remove extra refs in modules.sqf
  modules/kobld_billboards/images/cherno.jpg
  modules/kobld_billboards/images/coffee.jpg
  modules/kobld_billboards/images/waifu.jpg
  modules/kobld_billboards/init.sqf
  modules/kobld_billboards/preInitClient.sqf
  modules/kobld_billboards/preInitServer.sqf
  modules/kobld_billboards/root.sqf
  modules/kobld_billboards/script_component.hpp
  modules/kobld_billboards/settings.sqf
  modules/kobld_daylight/params.hpp
  modules/kobld_daylight/preInitClient.sqf
  modules/kobld_daylight/preInitServer.sqf
  modules/kobld_daylight/root.sqf
  modules/kobld_daylight/script_component.hpp
  modules/kobld_snow/functions/CfgFunctions.hpp
  modules/kobld_snow/functions/KOBLD_SNOW/fn_breathEffect.sqf
  modules/kobld_snow/functions/KOBLD_SNOW/fn_posCheck.sqf
  modules/kobld_snow/functions/KOBLD_SNOW/fn_shiver.sqf
  modules/kobld_snow/functions/KOBLD_SNOW/fn_snowFX.sqf
  modules/kobld_snow/functions/KOBLD_SNOW/fn_snow_drop.sqf
  modules/kobld_snow/functions/KOBLD_SNOW/script_component.hpp
  modules/kobld_snow/preInitClient.sqf
  modules/kobld_snow/root.sqf
  modules/kobld_snow/script_component.hpp
  modules/kobld_snow/settings.sqf
  modules/kobld_snow/sounds.hpp
  modules/kobld_snow/sounds/shiver_1.ogg
  modules/kobld_snow/sounds/shiver_2.ogg
  modules/kobld_snow/sounds/shiver_3.ogg
  modules/kobld_snow/sounds/shiver_4.ogg
  modules/modules.sqf
Labels: enhancement

#158 Missing gearSetting for removeAllGear.
  core/functions/fn_gearScript.sqf
  customization/gearSettings.sqf
Labels: bug

#157 Fixes for Capture zone
  modules/capture_zone/functions/CAPZONE/fn_setCaptureZone.sqf
  modules/capture_zone/functions/CAPZONE/fn_setColours.sqf
  modules/capture_zone/postInitServer.sqf
  modules/capture_zone/preInitClient.sqf
  modules/capture_zone/settings.sqf
Labels: bug

#159 Capture zone checking fixes.
  modules/capture_zone/functions/CAPZONE/fn_isCaptured.sqf
  modules/capture_zone/functions/CAPZONE/fn_setCaptureZone.sqf
  modules/capture_zone/postInitServer.sqf
  modules/capture_zone/preInitClient.sqf
Labels: bug

#160 cTab settings module.
  customization/vehGearSettings.sqf
  modules/cTab_settings/postInitServer.sqf
  modules/cTab_settings/preInitClient.sqf
  modules/cTab_settings/root.sqf
  modules/cTab_settings/script_component.hpp
  modules/cTab_settings/settings.sqf
  modules/modules.sqf
Labels: enhancement

#161 Default patrol distance setting
  modules/headless_ai/cfgFunctions/task/fn_taskAssign.sqf
Labels: bug

#165 Bugfix/individual team tickets
  core/functions/fn_spectatePrep.sqf
  core/preinitClient.sqf
  core/preinitServer.sqf
  customization/clientSettings.sqf
  customization/serverSettings.sqf
Labels: bug, enhancement

#162 Feature/notes
  modules/modules.sqf
  modules/notes/data/destroy.paa
  modules/notes/data/drop.paa
  modules/notes/data/give.paa
  modules/notes/data/note.paa
  modules/notes/data/notepad.paa
  modules/notes/data/read.paa
  modules/notes/data/write.paa
  modules/notes/dialog/baseDefines.hpp
  modules/notes/dialog/baseRsc.hpp
  modules/notes/dialog/defines.hpp
  modules/notes/dialog/diag.hpp
  modules/notes/dialog/dialog.hpp
  modules/notes/dialog/ui_toolkit.hpp
  modules/notes/functions/CfgFunctions.hpp
  modules/notes/functions/NOTES/fn_addSelfinteraction.sqf
  modules/notes/functions/NOTES/fn_allowInspection.sqf
  modules/notes/functions/NOTES/fn_allowWriting.sqf
  modules/notes/functions/NOTES/fn_delayedCall.sqf
  modules/notes/functions/NOTES/fn_destroyNote.sqf
  modules/notes/functions/NOTES/fn_dropNote.sqf
  modules/notes/functions/NOTES/fn_enterHint.sqf
  modules/notes/functions/NOTES/fn_generateName.sqf
  modules/notes/functions/NOTES/fn_giveNote.sqf
  modules/notes/functions/NOTES/fn_initNote.sqf
  modules/notes/functions/NOTES/fn_inspectNote.sqf
  modules/notes/functions/NOTES/fn_loadUI.sqf
  modules/notes/functions/NOTES/fn_playGiveAnimation.sqf
  modules/notes/functions/NOTES/fn_readNote.sqf
  modules/notes/functions/NOTES/fn_receiveNote.sqf
  modules/notes/functions/NOTES/fn_setAmount.sqf
  modules/notes/functions/NOTES/fn_setHandwriting.sqf
  modules/notes/functions/NOTES/fn_spawnNote.sqf
  modules/notes/functions/NOTES/fn_takeNote.sqf
  modules/notes/functions/NOTES/fn_uiDrop.sqf
  modules/notes/functions/NOTES/fn_uiSave.sqf
  modules/notes/functions/NOTES/fn_uiTakeDrop.sqf
  modules/notes/functions/NOTES/fn_updateMyNotes.sqf
  modules/notes/functions/NOTES/fn_writeNote.sqf
  modules/notes/functions/NOTES/script_component.hpp
  modules/notes/postInitClient.sqf
  modules/notes/root.sqf
  modules/notes/script_component.hpp
  modules/notes/settings.hpp
  modules/notes/sounds.hpp
  modules/notes/sounds/rip1.ogg
  modules/notes/sounds/rip2.ogg
  modules/notes/sounds/rip3.ogg
  modules/notes/sounds/rip4.ogg
Labels: enhancement

#164 Setup timer update
  core/dia/rscdefinitions.hpp
  modules/setup_timer/CfgNotifications.hpp
  modules/setup_timer/RscInit.sqf
  modules/setup_timer/RscSetupTimer.hpp
  modules/setup_timer/functions/CfgFunctions.hpp
  modules/setup_timer/functions/STIMER/fn_addSetupMarker.sqf
  modules/setup_timer/functions/STIMER/fn_timerInit.sqf
  modules/setup_timer/functions/STIMER/script_component.hpp
  modules/setup_timer/init.sqf
  modules/setup_timer/postInitClient.sqf
  modules/setup_timer/preInitClient.sqf
  modules/setup_timer/resources/setuptimermodule_ca.paa
  modules/setup_timer/root.sqf
  modules/setup_timer/script_component.hpp
  modules/setup_timer/settings.sqf
Labels: enhancement

#168 Feature/ai driver rewrite
  core/script_macros.hpp
  description.ext
  modules/ai_drivers/functions/AiDrivers/fn_AD_EnableAIDriver.sqf
  modules/ai_drivers/functions/AiDrivers/fn_AD_Init.sqf
  modules/ai_drivers/functions/AiDrivers/fn_AD_RemoveUnit.sqf
  modules/ai_drivers/functions/AiDrivers/fn_AD_ToggleDriverCam.sqf
  modules/ai_drivers/functions/AiDrivers/fn_createDriver.sqf
  modules/ai_drivers/functions/AiDrivers/fn_enableAIDriver.sqf
  modules/ai_drivers/functions/AiDrivers/fn_removeDriver.sqf
  modules/ai_drivers/functions/AiDrivers/fn_toggleDriverCam.sqf
  modules/ai_drivers/functions/AiDrivers/script_component.hpp
  modules/ai_drivers/functions/CfgFunctions.hpp
  modules/ai_drivers/postInitClient.sqf
  modules/ai_drivers/preinitClient.sqf
  modules/ai_drivers/root.sqf
  modules/ai_drivers/script_component.hpp
  modules/ai_drivers/settings.hpp
  modules/ai_drivers/settings.sqf
Labels: enhancement

#167 Bugfix/respawn messages
  core/functions/spectator/fn_startSpectator.sqf
  core/postInitClient.sqf
  core/preinitClient.sqf
Labels: bug

#169 Move settings to config format, add vehicle EH
  modules/anti_nd/functions/anti_nd/fn_Init.sqf
  modules/anti_nd/preinitClient.sqf
  modules/anti_nd/root.sqf
  modules/anti_nd/settings.hpp
Labels: enhancement

#170 AI Driver Unique Settings, RemoteExec SetEffectiveCommander
  modules/ai_drivers/functions/AiDrivers/fn_createDriver.sqf
  modules/ai_drivers/postInitClient.sqf
Labels: bug

#171 Fix preprecessor macros, empty vehicle param order
  description.ext
  modules/headless_ai/cfgFunctions/GetInfo/fn_getDetailsVehicleEmpty.sqf
  modules/headless_ai/cfgFunctions/GetInfo/fn_getSyncedObjects.sqf
  modules/headless_ai/cfgFunctions/create/fn_createEmptyVehicle.sqf
  modules/headless_ai/cfgFunctions/create/fn_createVehicle.sqf
  modules/headless_ai/root.sqf
Labels: bug

#175 IG Brief - Logics no longer need to be place
  modules/in_game_brief/functions/IGBRIEF/fn_register.sqf
  modules/in_game_brief/functions/IGBRIEF/fn_setup.sqf
  modules/in_game_brief/preInitClient.sqf
  modules/in_game_brief/settings.sqf
Labels: enhancement
